name: oak_openfeign_boot
description: openfeign dart  boot
version: 1.0.0
homepage: https://github.com/goeast9527/oak-dart-feign.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0 <=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  reflectable: ^4.0.12
  oak_dart_basic:
    git:
      https://github.com/goeast9527/oak-dart-basic.git
  oak_dart_openfeign:
    git: https://github.com/goeast9527/oak-dart-feign.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  quiver: ^3.2.2
  test: ^1.25.14
  build_runner: 2.4.10
  build_test: ^2.2.3
  # If you need to run web tests, you will also need this dependency.
  #  build_web_compilers: any
  built_value_generator: 8.5.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
